{"ray": {"sid": "863ab2ac67ac4ad5a0eadad3910dd161", "uid": null, "qid": "3ec0eb7e4c9343e4a243abd89d0c2eb5", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [3ec0eb7e4c9343e4a243abd89d0c2eb5]\nTraceback (most recent call last):\n  File \"C:\\Users\\avina\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openfabric_pysdk\\app\\worker.py\", line 90, in process\n    output = execution_callback_function(data, ray, self.state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\avina\\Downloads\\openfabric-ai-software-engineer 2\\openfabric-ai-software-engineer\\main.py\", line 144, in execute\n    if not model_set in state:\n           ^^^^^^^^^\nNameError: name 'model_set' is not defined\n", "created_at": "2023-12-31T08:17:14.134609"}], "status": "FAILED", "created_at": "2023-12-31T08:17:14.081199", "updated_at": "2023-12-31T08:17:14.137596", "finished": true}, "in": {"text": ["string"]}, "out": {}}