{"ray": {"sid": "dde827ef283446d78b9f0fd0787dee4e", "uid": null, "qid": "88b270195cca4b17b9aac864577aa977", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [88b270195cca4b17b9aac864577aa977]\nTraceback (most recent call last):\n  File \"C:\\Users\\avina\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openfabric_pysdk\\app\\worker.py\", line 90, in process\n    output = execution_callback_function(data, ray, self.state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\avina\\Downloads\\openfabric-ai-software-engineer 2\\openfabric-ai-software-engineer\\main.py\", line 153, in execute\n    response = agent_executor.run({\"input\": text})\n               ^^^^^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'agent_executor' where it is not associated with a value\n", "created_at": "2023-12-31T08:32:37.351241"}], "status": "FAILED", "created_at": "2023-12-31T08:32:37.228043", "updated_at": "2023-12-31T08:32:37.352272", "finished": true}, "in": {"text": ["string"]}, "out": {}}