{"ray": {"sid": "3f2a4725771542bb91b00384e68afbc9", "uid": null, "qid": "9af99c4bddb9430fa2eb236999ac9248", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [9af99c4bddb9430fa2eb236999ac9248]\nTraceback (most recent call last):\n  File \"C:\\Users\\avina\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openfabric_pysdk\\app\\worker.py\", line 90, in process\n    output = execution_callback_function(data, ray, self.state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\avina\\Downloads\\openfabric-ai-software-engineer 2\\openfabric-ai-software-engineer\\main.py\", line 128, in execute\n    agent_executor = get_model_state()\n                     ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\avina\\Downloads\\openfabric-ai-software-engineer 2\\openfabric-ai-software-engineer\\main.py\", line 73, in get_model_state\n    tools = load_tools([\"wikipedia\"], llm=llm)\n                                          ^^^\nUnboundLocalError: cannot access local variable 'llm' where it is not associated with a value\n", "created_at": "2023-12-30T12:47:41.512349"}], "status": "FAILED", "created_at": "2023-12-30T12:47:41.366539", "updated_at": "2023-12-30T12:47:41.525176", "finished": true}, "in": {"text": ["string"]}, "out": {}}